import {
  Student,
  Branch,
  Room,
  Seat,
  TestSeries,
  AuditLog,
  UserProfile,
  AttendanceRecord,
  AttendanceCorrection,
  GeofenceSettings,
  StudentDocument,
  Coupon,
  DigitalBook,
  InstitutionResult,
  Order,
  PaymentRecord,
  StudentIdCard,
  StaffIdCard,
  IdCardSettings,
  PaymentWebhookEvent,
  StudentNotice
} from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'usr-superadmin-01',
    role: 'SUPER_ADMIN',
    email: 'director@darulfaham.edu.in',
    displayName: 'Dr. Tariq Rahman (Super Admin)',
    staffId: 'DF-STF-2026-00000',
    permissions: ['all', 'security_audit', 'seat_management', 'test_engine', 'user_governance'],
  },
  {
    uid: 'usr-admin-01',
    role: 'ADMIN',
    email: 'admin.hazratganj@darulfaham.edu.in',
    displayName: 'Sayed Farhan (Branch Admin)',
    staffId: 'DF-STF-2026-00002',
    permissions: ['security_audit', 'seat_management', 'test_engine'],
  },
  {
    uid: 'usr-staff-01',
    role: 'STAFF',
    email: 'staff.reception@darulfaham.edu.in',
    displayName: 'Amina Khatun (Study Hall Warden)',
    staffId: 'DF-STF-2026-00001',
    permissions: ['attendance', 'seat_view'],
  },
  {
    uid: 'usr-student-01',
    role: 'STUDENT',
    email: 'zeeshan.alam@student.darulfaham.in',
    displayName: 'Zeeshan Alam (Student A)',
    studentId: 'DF-STU-2026-00001',
  },
  {
    uid: 'usr-student-02',
    role: 'STUDENT',
    email: 'fatima.zahra@student.darulfaham.in',
    displayName: 'Fatima Zahra (Student B)',
    studentId: 'DF-STU-2026-00002',
  },
];

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-central',
    name: 'DARULFAHAM Central Campus',
    location: 'Hazratganj Main Blvd, Civil Lines',
    city: 'Lucknow',
    totalRooms: 4,
  },
  {
    id: 'branch-north',
    name: 'DARULFAHAM North Campus',
    location: 'Sector C, Aliganj Knowledge Hub',
    city: 'Lucknow',
    totalRooms: 3,
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-101',
    branchId: 'branch-central',
    name: 'Silent Sanctum A (Air-Conditioned)',
    floor: '1st Floor',
    capacity: 25,
  },
  {
    id: 'room-102',
    branchId: 'branch-central',
    name: 'Research & Prelims Wing B',
    floor: '2nd Floor',
    capacity: 20,
  },
  {
    id: 'room-201',
    branchId: 'branch-north',
    name: 'Mains Collaborative Hall C',
    floor: 'Ground Floor',
    capacity: 25,
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    studentId: 'DF-STU-2026-00001',
    name: 'Zeeshan Alam',
    fatherName: 'Noor Mohammad Alam',
    motherName: 'Razia Begum',
    dob: '2001-08-14',
    address: '42/B, Cantonment Enclave, Lucknow, UP - 226002',
    phone: '+91 98390 12345',
    parentPhone: '+91 98390 99887',
    email: 'zeeshan.alam@student.darulfaham.in',
    aadhaarNumber: 'XXXX-XXXX-4819',
    aadhaarUrl: 'aadhaar/DF-STU-2026-00001/aadhaar_card.pdf',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    course: 'UPSC Civil Services Foundation 2026',
    membershipType: 'Sanctum 24/7 Dedicated',
    membershipExpiry: '2026-12-31',
    assignedSeatId: 'seat-room101-3',
    seatNumber: 3,
    roomName: 'Silent Sanctum A (Room 101)',
    branchId: 'branch-central',
    registeredDate: '2026-01-15',
  },
  {
    studentId: 'DF-STU-2026-00002',
    name: 'Fatima Zahra',
    fatherName: 'Dr. Aslam Siddiqui',
    motherName: 'Shabnam Siddiqui',
    dob: '2002-03-22',
    address: '18, Golf City Vista, Shaheed Path, Lucknow, UP',
    phone: '+91 97941 88231',
    parentPhone: '+91 97941 11223',
    email: 'fatima.zahra@student.darulfaham.in',
    aadhaarNumber: 'XXXX-XXXX-9023',
    aadhaarUrl: 'aadhaar/DF-STU-2026-00002/aadhaar_card.pdf',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    course: 'UPSC Prelims Intensive 2026',
    membershipType: 'Standard Sanctum Day Pass',
    membershipExpiry: '2026-11-15',
    assignedSeatId: 'seat-room101-8',
    seatNumber: 8,
    roomName: 'Silent Sanctum A (Room 101)',
    branchId: 'branch-central',
    registeredDate: '2026-01-18',
  },
  {
    studentId: 'DF-STU-2026-00003',
    name: 'Mohammad Bilal Qureshi',
    fatherName: 'Abdul Rashid Qureshi',
    motherName: 'Naseem Akhtar',
    dob: '2000-11-05',
    address: '77, Old Nazirabad, Aminabad, Lucknow, UP',
    phone: '+91 94150 44920',
    parentPhone: '+91 94150 77665',
    email: 'bilal.qureshi@student.darulfaham.in',
    aadhaarNumber: 'XXXX-XXXX-3341',
    aadhaarUrl: 'aadhaar/DF-STU-2026-00003/aadhaar_card.pdf',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    course: 'State PSC Prelims 2026',
    membershipType: 'Night Sanctum Scholar',
    membershipExpiry: '2026-10-31',
    assignedSeatId: 'seat-room101-12',
    seatNumber: 12,
    roomName: 'Silent Sanctum A (Room 101)',
    branchId: 'branch-central',
    registeredDate: '2026-02-01',
  },
  {
    studentId: 'DF-STU-2026-00004',
    name: 'Ayesha Mariyam',
    fatherName: 'Syed Irfan Hashmi',
    motherName: 'Zehra Hashmi',
    dob: '2003-05-19',
    address: 'Flat 402, Royal Towers, Gomti Nagar, Lucknow',
    phone: '+91 91612 99014',
    parentPhone: '+91 91612 33445',
    email: 'ayesha.m@student.darulfaham.in',
    aadhaarNumber: 'XXXX-XXXX-6129',
    aadhaarUrl: 'aadhaar/DF-STU-2026-00004/aadhaar_card.pdf',
    profilePhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'pending',
    branchId: 'branch-central',
    registeredDate: '2026-02-28',
  },
];

// Generate seats for Room 101, 102, 201
export const generateInitialSeats = (): Seat[] => {
  const seats: Seat[] = [];
  
  // Room 101 (25 seats)
  for (let i = 1; i <= 25; i++) {
    const isOccupiedByZeeshan = i === 3;
    const isOccupiedByFatima = i === 8;
    const isOccupiedByBilal = i === 12;
    const isOccupiedOther = i === 16 || i === 22;

    seats.push({
      id: `seat-room101-${i}`,
      branchId: 'branch-central',
      roomId: 'room-101',
      seatNumber: i,
      status: isOccupiedByZeeshan || isOccupiedByFatima || isOccupiedByBilal || isOccupiedOther ? 'occupied' : 'available',
      assignedTo: isOccupiedByZeeshan ? 'DF-STU-2026-00001' : isOccupiedByFatima ? 'DF-STU-2026-00002' : isOccupiedByBilal ? 'DF-STU-2026-00003' : isOccupiedOther ? `STU-PREV-${i}` : undefined,
      studentName: isOccupiedByZeeshan ? 'Zeeshan Alam' : isOccupiedByFatima ? 'Fatima Zahra' : isOccupiedByBilal ? 'Mohammad Bilal' : isOccupiedOther ? 'Rehan Ansari' : undefined,
      assignedAt: (isOccupiedByZeeshan || isOccupiedByFatima || isOccupiedByBilal || isOccupiedOther) ? '2026-02-01T09:00:00Z' : undefined
    });
  }

  // Room 102 (20 seats)
  for (let i = 1; i <= 20; i++) {
    const isOccupied = i === 2 || i === 7 || i === 15;
    seats.push({
      id: `seat-room102-${i}`,
      branchId: 'branch-central',
      roomId: 'room-102',
      seatNumber: i,
      status: isOccupied ? 'occupied' : 'available',
      assignedTo: isOccupied ? `STU-GEN-${i}` : undefined,
      studentName: isOccupied ? (i === 2 ? 'Kashif Mirza' : i === 7 ? 'Sana Parveen' : 'Hassan Raza') : undefined,
      assignedAt: isOccupied ? '2026-02-10T10:30:00Z' : undefined
    });
  }

  // Room 201 (25 seats)
  for (let i = 1; i <= 25; i++) {
    const isOccupied = i === 4 || i === 11 || i === 19;
    seats.push({
      id: `seat-room201-${i}`,
      branchId: 'branch-north',
      roomId: 'room-201',
      seatNumber: i,
      status: isOccupied ? 'occupied' : 'available',
      assignedTo: isOccupied ? `STU-NORTH-${i}` : undefined,
      studentName: isOccupied ? (i === 4 ? 'Owais Siddiqui' : i === 11 ? 'Nadia Sheikh' : 'Uzair Ali') : undefined,
      assignedAt: isOccupied ? '2026-02-15T08:00:00Z' : undefined
    });
  }

  return seats;
};

export const INITIAL_TEST_SERIES: TestSeries[] = [
  {
    id: 'series-01',
    title: 'DARULFAHAM GS-I Prelims Elite Mock 2026',
    description: 'High-yield examination testing Indian Polity, Modern History, Geography, and Current Economic Developments with full analytical breakdowns.',
    category: 'General Studies',
    price: 0,
    enrolledCount: 142,
    tests: [
      {
        id: 'test-polity-01',
        title: 'Constitutional Law & Governance Mock Test 01',
        subject: 'Indian Polity',
        durationMinutes: 15,
        totalQuestions: 6,
        totalMarks: 30,
        questions: [
          {
            id: 'q1',
            question: 'Under Article 32 of the Constitution of India, which of the following writs is issued to safeguard personal liberty against illegal detention?',
            options: ['Mandamus', 'Habeas Corpus', 'Quo-Warranto', 'Certiorari'],
            correctOptionIndex: 1,
            explanation: 'Habeas Corpus literally translates to "You may have the body". It protects individuals from unlawful or arbitrary executive arrest.',
            marks: 5,
          },
          {
            id: 'q2',
            question: 'Which constitutional amendment incorporated the Fundamental Duties under Part IVA (Article 51A)?',
            options: ['42nd Constitutional Amendment Act, 1976', '44th Constitutional Amendment Act, 1978', '86th Constitutional Amendment Act, 2002', '52nd Constitutional Amendment Act, 1985'],
            correctOptionIndex: 0,
            explanation: 'The 42nd Amendment in 1976 added 10 fundamental duties recommended by the Swaran Singh Committee. The 11th duty was added by the 86th amendment in 2002.',
            marks: 5,
          },
          {
            id: 'q3',
            question: 'The doctrine of "Basic Structure" of the Indian Constitution was propounded by the Supreme Court in which landmark case?',
            options: ['Golaknath case (1967)', 'Kesavananda Bharati case (1973)', 'Minerva Mills case (1980)', 'Maneka Gandhi case (1978)'],
            correctOptionIndex: 1,
            explanation: 'The landmark 13-judge bench in Kesavananda Bharati v. State of Kerala (1973) held that Parliament cannot alter the basic features of the Constitution under Article 368.',
            marks: 5,
          },
          {
            id: 'q4',
            question: 'Money Bills can be introduced only in which house of the Indian Parliament?',
            options: ['Lok Sabha only', 'Rajya Sabha only', 'Either Lok Sabha or Rajya Sabha', 'Joint Sitting of both Houses'],
            correctOptionIndex: 0,
            explanation: 'Under Article 109, a Money Bill can only be introduced in the Lok Sabha with prior recommendation of the President.',
            marks: 5,
          },
          {
            id: 'q5',
            question: 'Which schedule of the Indian Constitution contains provisions regarding the administration and control of Scheduled Areas and Scheduled Tribes?',
            options: ['Fifth Schedule', 'Sixth Schedule', 'Seventh Schedule', 'Eighth Schedule'],
            correctOptionIndex: 0,
            explanation: 'The Fifth Schedule deals with administration of Scheduled Areas and Tribes in states other than Assam, Meghalaya, Tripura, and Mizoram (which are covered under the Sixth Schedule).',
            marks: 5,
          },
          {
            id: 'q6',
            question: 'The tenure of the Comptroller and Auditor General (CAG) of India is:',
            options: ['5 years or up to 65 years of age', '6 years or up to 65 years of age', '5 years or up to 62 years of age', 'At the pleasure of the President'],
            correctOptionIndex: 1,
            explanation: 'Under Article 148, the CAG holds office for a term of 6 years or until attaining the age of 65 years, whichever is earlier.',
            marks: 5,
          }
        ]
      },
      {
        id: 'test-history-02',
        title: 'Modern Indian History & Freedom Movement Test 02',
        subject: 'Modern History',
        durationMinutes: 10,
        totalQuestions: 4,
        totalMarks: 20,
        questions: [
          {
            id: 'hq1',
            question: 'Who among the following was the founder of the Indian National Social Conference in 1887?',
            options: ['M.G. Ranade and Raghunath Rao', 'B.G. Tilak', 'Gopal Krishna Gokhale', 'Dadabhai Naoroji'],
            correctOptionIndex: 0,
            explanation: 'Founded by M.G. Ranade and Raghunath Rao, it advocated for eradication of child marriage, dowry, and female illiteracy.',
            marks: 5,
          },
          {
            id: 'hq2',
            question: 'The historic Champaran Satyagraha of Mahatma Gandhi (1917) was related to which issue?',
            options: ['Cotton mill workers bonus', 'Tinkathia system of indigo cultivation', 'Salt law taxation', 'High land revenue during drought'],
            correctOptionIndex: 1,
            explanation: 'Peasants were forced under the Tinkathia system to grow indigo on 3/20th of their land holding.',
            marks: 5,
          },
          {
            id: 'hq3',
            question: 'Which British Viceroy announced the Partition of Bengal in 1905?',
            options: ['Lord Curzon', 'Lord Minto', 'Lord Hardinge', 'Lord Chelmsford'],
            correctOptionIndex: 0,
            explanation: 'Lord Curzon issued the order dividing Bengal on October 16, 1905, triggering the Swadeshi and Boycott movement.',
            marks: 5,
          },
          {
            id: 'hq4',
            question: 'The Cabinet Mission of 1946 rejected the demand for:',
            options: ['Interim Government', 'A full-fledged sovereign Pakistan', 'A Constituent Assembly', 'Federal Union of India'],
            correctOptionIndex: 1,
            explanation: 'The Cabinet Mission Plan specifically turned down the creation of a separate sovereign Pakistan, proposing an undivided Indian Union with a three-tier federation.',
            marks: 5,
          }
        ]
      }
    ]
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    adminId: 'usr-superadmin-01',
    adminName: 'Dr. Tariq Rahman (Super Admin)',
    action: 'VIEW_AADHAAR_DOCUMENT',
    targetStudent: 'DF-STU-2026-00001',
    targetStudentName: 'Zeeshan Alam',
    timestamp: '2026-09-04T10:14:22Z',
    severity: 'high',
    ip: '192.168.1.104',
    details: 'Decrypted Aadhaar document vault for student verification under UIDAI guidelines.',
  },
  {
    id: 'log-002',
    adminId: 'usr-superadmin-01',
    adminName: 'Dr. Tariq Rahman (Super Admin)',
    action: 'ID_CARD_GENERATED',
    targetStudent: 'DF-STU-2026-00001',
    targetStudentName: 'Zeeshan Alam',
    timestamp: '2026-09-04T10:18:00Z',
    severity: 'low',
    ip: '192.168.1.104',
    details: 'Generated official Digital Student ID Card DF-STU-2026-00001 with cryptographically signed verification QR.',
  },
  {
    id: 'log-003',
    adminId: 'usr-admin-01',
    adminName: 'Sayed Farhan (Branch Admin)',
    action: 'ASSIGN_SEAT',
    targetStudent: 'DF-STU-2026-00002',
    targetStudentName: 'Fatima Zahra',
    timestamp: '2026-09-03T14:30:10Z',
    severity: 'medium',
    ip: '192.168.1.112',
    details: 'Allocated Seat #8 in Silent Sanctum A (Room 101).',
  },
  {
    id: 'log-004',
    adminId: 'usr-admin-01',
    adminName: 'Sayed Farhan (Branch Admin)',
    action: 'REGISTER_STUDENT',
    targetStudent: 'DF-STU-2026-00004',
    targetStudentName: 'Ayesha Mariyam',
    timestamp: '2026-09-02T11:05:44Z',
    severity: 'medium',
    ip: '192.168.1.112',
    details: 'Enrolled under DF-STU-2026 series with pending document review.',
  },
  {
    id: 'log-005',
    adminId: 'usr-superadmin-01',
    adminName: 'Dr. Tariq Rahman (Super Admin)',
    action: 'SECURITY_SETTINGS_CHANGE',
    timestamp: '2026-09-01T08:00:00Z',
    severity: 'high',
    ip: '192.168.1.104',
    details: 'Enforced Zero-Trust Student Privacy: Audit logs removed from student visibility; phone numbers masked from peers.',
  },
  {
    id: 'log-006',
    adminId: 'usr-admin-01',
    adminName: 'Sayed Farhan (Branch Admin)',
    action: 'PAYMENT_STATUS_CHANGE',
    targetStudent: 'DF-STU-2026-00001',
    targetStudentName: 'Zeeshan Alam',
    timestamp: '2026-08-15T14:22:00Z',
    severity: 'medium',
    ip: '192.168.1.112',
    details: 'Order ord-1002 marked SUCCESS via Cashfree Gateway server reconciliation.',
  },
  {
    id: 'log-007',
    adminId: 'usr-superadmin-01',
    adminName: 'Dr. Tariq Rahman (Super Admin)',
    action: 'ID_CARD_STATUS_CHANGE',
    targetStudent: 'DF-STU-2026-00004',
    targetStudentName: 'Ayesha Mariyam',
    timestamp: '2026-08-28T16:45:00Z',
    severity: 'medium',
    ip: '192.168.1.104',
    details: 'Student ID Card DF-STU-2026-00004 set to INACTIVE pending Aadhaar identity confirmation.',
  }
];

export const INITIAL_GEOFENCE_SETTINGS: GeofenceSettings = {
  id: 'geo-hazratganj-main',
  premisesName: 'DARULFAHAM Central Study Sanctum (Hazratganj Campus)',
  latitude: 26.8467,
  longitude: 80.9462,
  allowedRadiusMeters: 100,
  isActive: true,
  requireFaceVerification: true,
  requireLocation: true,
  updatedAt: '2026-09-01T08:00:00Z',
  updatedBy: 'Dr. Tariq Rahman (Super Admin)',
};

export const INITIAL_ATTENDANCE_CORRECTIONS: AttendanceCorrection[] = [
  {
    id: 'cor-01',
    attendanceId: 'att-zeesh-22',
    studentId: 'DF-STU-2026-00001',
    studentName: 'Zeeshan Alam',
    date: '2026-08-25',
    previousStatus: 'absent',
    newStatus: 'present',
    reason: 'Student was present in Sanctum Room 101 but biometric verification failed due to network glitch.',
    changedBy: 'usr-admin-01',
    changedByName: 'Sayed Farhan (Branch Admin)',
    changedAt: '2026-08-25T11:30:00Z',
  },
];

export const INITIAL_STUDENT_DOCUMENTS: StudentDocument[] = [
  {
    id: 'doc-zeesh-01',
    studentId: 'DF-STU-2026-00001',
    documentType: 'STUDENT_PHOTO',
    documentName: 'zeeshan_passport_photo.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    fileSize: 245000,
    mimeType: 'image/jpeg',
    uploadedAt: '2026-01-15T10:00:00Z',
    uploadedBy: 'usr-student-01',
    status: 'VERIFIED',
    isSensitive: false,
  },
  {
    id: 'doc-zeesh-02',
    studentId: 'DF-STU-2026-00001',
    documentType: 'AADHAAR_CARD',
    documentName: 'aadhaar_card_DF-STU-2026-00001.pdf',
    fileUrl: 'aadhaar/DF-STU-2026-00001/aadhaar_card.pdf',
    fileSize: 412000,
    mimeType: 'application/pdf',
    uploadedAt: '2026-01-15T10:05:00Z',
    uploadedBy: 'usr-student-01',
    status: 'VERIFIED',
    isSensitive: true,
  },
  {
    id: 'doc-fatima-01',
    studentId: 'DF-STU-2026-00002',
    documentType: 'STUDENT_PHOTO',
    documentName: 'fatima_profile.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    fileSize: 198000,
    mimeType: 'image/jpeg',
    uploadedAt: '2026-01-18T11:20:00Z',
    uploadedBy: 'usr-student-02',
    status: 'VERIFIED',
    isSensitive: false,
  },
  {
    id: 'doc-fatima-02',
    studentId: 'DF-STU-2026-00002',
    documentType: 'AADHAAR_CARD',
    documentName: 'aadhaar_card_DF-STU-2026-00002.pdf',
    fileUrl: 'aadhaar/DF-STU-2026-00002/aadhaar_card.pdf',
    fileSize: 389000,
    mimeType: 'application/pdf',
    uploadedAt: '2026-01-18T11:25:00Z',
    uploadedBy: 'usr-student-02',
    status: 'VERIFIED',
    isSensitive: true,
  },
];

// Helper to generate a realistic 25-day attendance history for Student A (23 present, 2 absent = 92%)
const generateStudentAttendance = (): AttendanceRecord[] => {
  const records: AttendanceRecord[] = [];
  const dates = [
    '2026-08-01', '2026-08-02', '2026-08-04', '2026-08-05', '2026-08-06',
    '2026-08-07', '2026-08-08', '2026-08-09', '2026-08-11', '2026-08-12',
    '2026-08-13', '2026-08-14', '2026-08-16', '2026-08-17', '2026-08-18',
    '2026-08-19', '2026-08-20', '2026-08-21', '2026-08-23', '2026-08-24',
    '2026-08-25', '2026-08-26', '2026-08-27', '2026-08-28', '2026-09-05'
  ];

  // Student A: 23 Present, 2 Absent (Dates index 4 and index 14 are absent)
  dates.forEach((dateStr, idx) => {
    const isAbsent = idx === 4 || idx === 14;
    records.push({
      id: `att-zeesh-${idx + 1}`,
      studentId: 'DF-STU-2026-00001',
      studentName: 'Zeeshan Alam',
      studentPhotoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      classLevel: 'UPSC Civil Services Foundation 2026',
      membershipType: 'Sanctum 24/7 Dedicated',
      branchId: 'branch-central',
      date: dateStr,
      checkIn: isAbsent ? '--' : `08:${(10 + (idx % 25)).toString().padStart(2, '0')} AM`,
      checkOut: isAbsent ? '--' : '06:30 PM',
      status: isAbsent ? 'absent' : 'present',
      seatNumber: 3,
      locationVerified: !isAbsent,
      faceVerified: !isAbsent,
      verificationMethod: isAbsent ? 'PENDING' : 'LOCATION_FACE',
      distanceMeters: isAbsent ? undefined : 32 + (idx % 40),
      createdAt: `${dateStr}T08:15:00Z`,
    });
  });

  // Student B: 24 Present, 1 Absent (Date index 8 absent)
  dates.forEach((dateStr, idx) => {
    const isAbsent = idx === 8;
    records.push({
      id: `att-fatima-${idx + 1}`,
      studentId: 'DF-STU-2026-00002',
      studentName: 'Fatima Zahra',
      studentPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      classLevel: 'UPSC Prelims Intensive 2026',
      membershipType: 'Standard Sanctum Day Pass',
      branchId: 'branch-central',
      date: dateStr,
      checkIn: isAbsent ? '--' : `08:${(20 + (idx % 15)).toString().padStart(2, '0')} AM`,
      checkOut: isAbsent ? '--' : '05:45 PM',
      status: isAbsent ? 'absent' : 'present',
      seatNumber: 8,
      locationVerified: !isAbsent,
      faceVerified: !isAbsent,
      verificationMethod: isAbsent ? 'PENDING' : 'LOCATION_FACE',
      distanceMeters: isAbsent ? undefined : 28 + (idx % 35),
      createdAt: `${dateStr}T08:25:00Z`,
    });
  });

  // Student C: Mohammad Bilal
  records.push({
    id: 'att-bilal-01',
    studentId: 'DF-STU-2026-00003',
    studentName: 'Mohammad Bilal Qureshi',
    studentPhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    classLevel: 'State PSC Prelims 2026',
    membershipType: 'Night Sanctum Scholar',
    branchId: 'branch-central',
    date: '2026-09-05',
    checkIn: '09:02 AM',
    checkOut: '08:00 PM',
    status: 'late',
    seatNumber: 12,
    locationVerified: true,
    faceVerified: true,
    verificationMethod: 'LOCATION_FACE',
    distanceMeters: 45,
    createdAt: '2026-09-05T09:02:00Z',
  });

  // Student D: Ayesha Mariyam
  records.push({
    id: 'att-ayesha-01',
    studentId: 'DF-STU-2026-00004',
    studentName: 'Ayesha Mariyam',
    studentPhotoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    classLevel: 'UPSC Civil Services Foundation 2026',
    membershipType: 'Sanctum 24/7 Dedicated',
    branchId: 'branch-central',
    date: '2026-09-05',
    checkIn: '08:45 AM',
    status: 'present',
    seatNumber: 15,
    locationVerified: true,
    faceVerified: false,
    verificationMethod: 'LOCATION_ONLY',
    distanceMeters: 62,
    createdAt: '2026-09-05T08:45:00Z',
  });

  return records;
};

export const INITIAL_ATTENDANCE: AttendanceRecord[] = generateStudentAttendance();

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-100',
    code: 'DARUL100',
    title: 'Flat ₹100 Off',
    description: 'Get flat ₹100 discount on any purchase above ₹500 across Test Series, Memberships & Books.',
    discountType: 'FLAT',
    discountValue: 100,
    minPurchase: 500,
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-12-31T23:59:59Z',
    usageLimit: 1000,
    perStudentLimit: 2,
    usageCount: 142,
    applicableProducts: ['ALL'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'coup-50',
    code: 'WELCOME50',
    title: 'Welcome Aspirant Bonus',
    description: 'Special ₹50 discount for newly enrolled students on any academic item.',
    discountType: 'FLAT',
    discountValue: 50,
    minPurchase: 200,
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-12-31T23:59:59Z',
    usageLimit: 2000,
    perStudentLimit: 1,
    usageCount: 88,
    applicableProducts: ['ALL'],
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'coup-2026',
    code: 'CIVIL2026',
    title: '20% Off Test Series',
    description: 'Enjoy 20% discount (up to ₹400) on all Prelims and Mains Test Series packages.',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minPurchase: 800,
    maxDiscount: 400,
    validFrom: '2026-01-15T00:00:00Z',
    validUntil: '2026-10-31T23:59:59Z',
    usageLimit: 500,
    perStudentLimit: 1,
    usageCount: 65,
    applicableProducts: ['TEST_SERIES', 'COURSE'],
    isActive: true,
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: 'coup-sanctum',
    code: 'SANCTUM25',
    title: '25% Study Space Subsidy',
    description: '25% discount (up to ₹500) on monthly Silent Sanctum study space reservations.',
    discountType: 'PERCENTAGE',
    discountValue: 25,
    minPurchase: 1200,
    maxDiscount: 500,
    validFrom: '2026-02-01T00:00:00Z',
    validUntil: '2026-12-31T23:59:59Z',
    usageLimit: 300,
    perStudentLimit: 1,
    usageCount: 39,
    applicableProducts: ['MEMBERSHIP', 'MEMBERSHIP_RENEWAL'],
    isActive: true,
    createdAt: '2026-02-01T00:00:00Z',
  },
];

export const INITIAL_DIGITAL_BOOKS: DigitalBook[] = [
  {
    id: 'book-01',
    title: 'Indian Polity & Governance: Complete Prelims & Mains Compendium',
    author: 'DARULFAHAM Senior Faculty Board',
    description: 'A comprehensive, chapter-by-chapter analytical guide covering constitutional provisions, landmark judicial doctrines, parliamentary procedures, and statutory commissions.',
    subject: 'Polity & Constitution',
    classLevel: 'UPSC CSE / State PSC',
    category: 'Core Text',
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&auto=format&fit=crop&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFree: true,
    price: 0,
    accessType: 'STUDENT',
    allowDownload: true,
    publicationDate: '2026-01-10',
    status: 'PUBLISHED',
    pageCount: 384,
    fileSizeBytes: 14500000,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'book-02',
    title: 'Advanced Ethics, Integrity & Aptitude: 100 Case Studies (GS Paper IV)',
    author: 'Prof. Asadullah Farooqi & Team',
    description: 'Pragmatic ethical frameworks, administrative dilemmas, Nolan committee principles, and step-by-step solved case studies for Civil Services aspirants.',
    subject: 'Ethics (GS-IV)',
    classLevel: 'UPSC CSE Mains',
    category: 'Case Studies',
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFree: false,
    price: 349,
    accessType: 'PAID',
    allowDownload: false,
    publicationDate: '2026-02-05',
    status: 'PUBLISHED',
    pageCount: 260,
    fileSizeBytes: 9800000,
    createdAt: '2026-02-05T12:00:00Z',
    updatedAt: '2026-02-05T12:00:00Z',
  },
  {
    id: 'book-03',
    title: 'Modern Indian History & Freedom Movement Master Notes',
    author: 'DARULFAHAM History Research Group',
    description: 'Chronological events from 1757 to 1947, tribal and peasant uprisings, socio-religious reform movements, and nationalist leadership analysis.',
    subject: 'History',
    classLevel: 'Foundation to Advanced',
    category: 'Revision Notes',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=400&auto=format&fit=crop&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFree: false,
    price: 249,
    accessType: 'MEMBERSHIP',
    allowDownload: true,
    publicationDate: '2026-01-20',
    status: 'PUBLISHED',
    pageCount: 195,
    fileSizeBytes: 8200000,
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 'book-04',
    title: 'Quantitative Aptitude, Data Interpretation & Logical Reasoning Masterbook',
    author: 'Er. S. K. Verma (IIT Alumni)',
    description: 'High-yield shortcuts, mental arithmetic, syllogisms, graphical interpretation, and 500+ practice problems tailored for CSAT and competitive exams.',
    subject: 'CSAT / Aptitude',
    classLevel: 'Prelims Stage',
    category: 'Practice Workbook',
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFree: false,
    price: 199,
    accessType: 'PAID',
    allowDownload: true,
    publicationDate: '2026-02-14',
    status: 'PUBLISHED',
    pageCount: 310,
    fileSizeBytes: 11200000,
    createdAt: '2026-02-14T11:00:00Z',
    updatedAt: '2026-02-14T11:00:00Z',
  },
  {
    id: 'book-05',
    title: 'DARULFAHAM Academic Charter & Competitive Syllabus Roadmap',
    author: 'Academic Council of DARULFAHAM',
    description: 'Official blueprint of institutional study tracks, syllabus weightage matrices, time management regimes, and library protocol guidelines.',
    subject: 'General / Orientation',
    classLevel: 'Open Access',
    category: 'Handbook',
    coverImage: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&auto=format&fit=crop&q=80',
    pdfUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFree: true,
    price: 0,
    accessType: 'PUBLIC',
    allowDownload: true,
    publicationDate: '2026-01-01',
    status: 'PUBLISHED',
    pageCount: 64,
    fileSizeBytes: 3400000,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-01-01T08:00:00Z',
  },
];

export const INITIAL_INSTITUTION_RESULTS: InstitutionResult[] = [
  {
    id: 'res-2025-01',
    academicYear: '2025-26',
    exam: 'UPSC Civil Services Examination',
    classLevel: 'UPSC CSE (IAS/IPS)',
    studentId: 'DF-2026-00001',
    studentName: 'Zeeshan Alam',
    displayNameType: 'FULL',
    marks: 1042,
    maxMarks: 1750,
    percentage: 59.5,
    rank: 42,
    subject: 'Political Science & IR Optional',
    achievement: 'All India Rank 42 — Recommended for IAS',
    description: 'Enrolled in DARULFAHAM Full-Time Sanctum Study Track and Intensive Mock Test Series. Scored exceptional marks in GS Paper II and Optional.',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    showPhoto: true,
    showMarks: true,
    showPercentage: true,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-05-10T10:00:00Z',
  },
  {
    id: 'res-2025-02',
    academicYear: '2025-26',
    exam: 'JKPSC Combined Competitive Examination (JKAS)',
    classLevel: 'State Administrative Services',
    studentId: 'DF-2026-00002',
    studentName: 'Fatima Zahra',
    displayNameType: 'INITIALS',
    customDisplayName: 'Fatima Z.',
    marks: 896,
    maxMarks: 1400,
    percentage: 64.0,
    rank: 8,
    subject: 'General Studies & Public Administration',
    achievement: 'Rank 8 — Junior Administrative Cadre',
    description: 'Consistent participant in DARULFAHAM Sunday Evaluated Tests and Silent Sanctum library member.',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    showPhoto: false,
    showMarks: true,
    showPercentage: true,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: '2026-06-15T11:30:00Z',
    updatedAt: '2026-06-15T11:30:00Z',
  },
  {
    id: 'res-2024-01',
    academicYear: '2024-25',
    exam: 'JKBOSE Higher Secondary Class 12 Boards',
    classLevel: 'Class 12 (Science Stream)',
    studentName: 'Aspirant #DF-2024-88',
    displayNameType: 'ANONYMOUS',
    customDisplayName: 'Aspirant #DF-2024-88',
    marks: 491,
    maxMarks: 500,
    percentage: 98.2,
    rank: 1,
    subject: 'Physics, Chemistry, Mathematics',
    achievement: 'State Board Gold Medalist & District Topper',
    description: 'Achieved outstanding 98.2% aggregate utilizing DARULFAHAM concept notes and revision sanctum.',
    showPhoto: false,
    showMarks: true,
    showPercentage: true,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: '2025-07-02T14:00:00Z',
    updatedAt: '2025-07-02T14:00:00Z',
  },
  {
    id: 'res-2024-02',
    academicYear: '2024-25',
    exam: 'All-India Prelims Marathon Mock League',
    classLevel: 'General Studies Paper I',
    studentId: 'DF-2026-00003',
    studentName: 'Mohammad Bilal Qureshi',
    displayNameType: 'FULL',
    marks: 148,
    maxMarks: 200,
    percentage: 74.0,
    rank: 3,
    subject: 'General Studies I',
    achievement: 'State 3rd Rank in Marathon Test Series',
    description: 'Mastered speed and negative marking avoidance using DARULFAHAM Online Test Engine.',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    showPhoto: true,
    showMarks: true,
    showPercentage: true,
    isFeatured: false,
    status: 'PUBLISHED',
    createdAt: '2025-10-18T16:00:00Z',
    updatedAt: '2025-10-18T16:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    studentId: 'DF-2026-00001',
    studentName: 'Zeeshan Alam',
    studentEmail: 'zeeshan.alam@student.darulfaham.in',
    studentPhone: '+91 98390 12345',
    productType: 'MEMBERSHIP',
    productId: 'seat-room101-3',
    productTitle: 'Study Space Monthly Sanctum Membership (Room 101, Seat 3)',
    originalAmount: 1500,
    couponCode: 'DARUL100',
    discountAmount: 100,
    finalAmount: 1400,
    currency: 'INR',
    status: 'PAID',
    cashfreeOrderId: 'CF_ORD_982144321',
    cashfreePaymentSessionId: 'session_cf_live_sample_01',
    paymentMethod: 'UPI / NetBanking',
    createdAt: '2026-08-01T10:15:00Z',
    updatedAt: '2026-08-01T10:16:30Z',
  },
  {
    id: 'ord-1002',
    studentId: 'DF-2026-00001',
    studentName: 'Zeeshan Alam',
    studentEmail: 'zeeshan.alam@student.darulfaham.in',
    studentPhone: '+91 98390 12345',
    productType: 'TEST_SERIES',
    productId: 'ts-upsc-prelims-2026',
    productTitle: 'UPSC Civil Services Prelims 2026 All-India Test Series',
    originalAmount: 1499,
    couponCode: 'CIVIL2026',
    discountAmount: 300,
    finalAmount: 1199,
    currency: 'INR',
    status: 'PAID',
    cashfreeOrderId: 'CF_ORD_982188440',
    cashfreePaymentSessionId: 'session_cf_live_sample_02',
    paymentMethod: 'Credit Card',
    createdAt: '2026-08-15T14:20:00Z',
    updatedAt: '2026-08-15T14:21:40Z',
  },
  {
    id: 'ord-1003',
    studentId: 'DF-2026-00002',
    studentName: 'Fatima Zahra',
    studentEmail: 'fatima.zahra@student.darulfaham.in',
    studentPhone: '+91 97941 88231',
    productType: 'MEMBERSHIP',
    productId: 'seat-room101-8',
    productTitle: 'Study Space Monthly Sanctum Membership (Room 101, Seat 8)',
    originalAmount: 1500,
    couponCode: 'SANCTUM25',
    discountAmount: 375,
    finalAmount: 1125,
    currency: 'INR',
    status: 'PAID',
    cashfreeOrderId: 'CF_ORD_982210192',
    cashfreePaymentSessionId: 'session_cf_live_sample_03',
    paymentMethod: 'UPI',
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-08-05T09:02:00Z',
  }
];

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    orderId: 'ord-1001',
    studentId: 'DF-STU-2026-00001',
    studentName: 'Zeeshan Alam',
    productTitle: 'Study Space Monthly Sanctum Membership (Room 101, Seat 3)',
    productType: 'MEMBERSHIP',
    originalAmount: 1500,
    discountAmount: 100,
    finalAmount: 1400,
    currency: 'INR',
    paymentMethod: 'UPI (GPay / PhonePe)',
    cashfreeReference: 'cf_ref_tx_90124881',
    receiptNumber: 'RCP-2026-0814',
    status: 'SUCCESS',
    paidAt: '2026-08-01T10:16:30Z',
    createdAt: '2026-08-01T10:16:30Z',
  },
  {
    id: 'pay-002',
    orderId: 'ord-1002',
    studentId: 'DF-STU-2026-00001',
    studentName: 'Zeeshan Alam',
    productTitle: 'UPSC Civil Services Prelims 2026 All-India Test Series',
    productType: 'TEST_SERIES',
    originalAmount: 1499,
    discountAmount: 300,
    finalAmount: 1199,
    currency: 'INR',
    paymentMethod: 'MasterCard / Visa',
    cashfreeReference: 'cf_ref_tx_90159920',
    receiptNumber: 'RCP-2026-0922',
    status: 'SUCCESS',
    paidAt: '2026-08-15T14:21:40Z',
    createdAt: '2026-08-15T14:21:40Z',
  },
  {
    id: 'pay-003',
    orderId: 'ord-1003',
    studentId: 'DF-STU-2026-00002',
    studentName: 'Fatima Zahra',
    productTitle: 'Study Space Monthly Sanctum Membership (Room 101, Seat 8)',
    productType: 'MEMBERSHIP',
    originalAmount: 1500,
    discountAmount: 375,
    finalAmount: 1125,
    currency: 'INR',
    paymentMethod: 'UPI / BharatQR',
    cashfreeReference: 'cf_ref_tx_90199104',
    receiptNumber: 'RCP-2026-1045',
    status: 'SUCCESS',
    paidAt: '2026-08-05T09:02:00Z',
    createdAt: '2026-08-05T09:02:00Z',
  }
];

export const INITIAL_STUDENT_ID_CARDS: StudentIdCard[] = [
  {
    id: 'card-stu-00001',
    studentId: 'DF-STU-2026-00001',
    studentName: 'Zeeshan Alam',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    course: 'UPSC Civil Services Foundation 2026-27',
    membershipType: 'Sanctum 24/7 Dedicated Cubicle',
    validUntil: '2026-12-31',
    issueDate: '2026-01-15',
    branchName: 'DARULFAHAM Central Campus',
    branchLocation: 'Hazratganj, Lucknow',
    assignedSeat: 'Seat #3 (Hall A)',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STU-2026-00001&token=df_v_98231',
    verificationToken: 'df_v_98231',
    status: 'ACTIVE',
    bloodGroup: 'B+',
    emergencyContact: '+91 522 400 9999 (DARULFAHAM Desk)',
    showPhoneOnCard: false,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'card-stu-00002',
    studentId: 'DF-STU-2026-00002',
    studentName: 'Fatima Zahra',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    course: 'UPSC Prelims-cum-Mains Advanced 2026',
    membershipType: 'Sanctum 24/7 Dedicated Cubicle',
    validUntil: '2026-12-31',
    issueDate: '2026-01-18',
    branchName: 'DARULFAHAM Central Campus',
    branchLocation: 'Hazratganj, Lucknow',
    assignedSeat: 'Seat #8 (Hall A)',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STU-2026-00002&token=df_v_44901',
    verificationToken: 'df_v_44901',
    status: 'ACTIVE',
    bloodGroup: 'O+',
    emergencyContact: '+91 522 400 9999 (DARULFAHAM Desk)',
    showPhoneOnCard: false,
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'card-stu-00003',
    studentId: 'DF-STU-2026-00003',
    studentName: 'Mohammad Bilal Qureshi',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    course: 'State PCS & Civil Services Intensive',
    membershipType: 'Day Sanctum (07:00 - 19:00)',
    validUntil: '2026-10-31',
    issueDate: '2026-02-01',
    branchName: 'DARULFAHAM Central Campus',
    branchLocation: 'Hazratganj, Lucknow',
    assignedSeat: 'Seat #12 (Hall A)',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STU-2026-00003&token=df_v_22910',
    verificationToken: 'df_v_22910',
    status: 'ACTIVE',
    bloodGroup: 'A+',
    emergencyContact: '+91 522 400 9999 (DARULFAHAM Desk)',
    showPhoneOnCard: false,
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 'card-stu-00004',
    studentId: 'DF-STU-2026-00004',
    studentName: 'Ayesha Mariyam',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    course: 'UPSC Civil Services Foundation 2026',
    membershipType: 'Pending Verification',
    validUntil: '2026-12-31',
    issueDate: '2026-02-28',
    branchName: 'DARULFAHAM Central Campus',
    branchLocation: 'Hazratganj, Lucknow',
    assignedSeat: 'Unassigned',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STU-2026-00004&token=df_v_11894',
    verificationToken: 'df_v_11894',
    status: 'INACTIVE',
    bloodGroup: 'AB+',
    emergencyContact: '+91 522 400 9999 (DARULFAHAM Desk)',
    showPhoneOnCard: false,
    createdAt: '2026-02-28T10:00:00Z',
    updatedAt: '2026-02-28T10:00:00Z',
  }
];

export const INITIAL_STAFF_ID_CARDS: StaffIdCard[] = [
  {
    id: 'card-stf-00001',
    staffId: 'DF-STF-2026-00001',
    staffName: 'Amina Khatun',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    designation: 'Senior Academic Proctor & Sanctum Warden',
    department: 'Sanctum Operations & Discipline',
    branchName: 'DARULFAHAM Central Campus',
    joiningDate: '2025-03-10',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STF-2026-00001&token=df_stf_8911',
    verificationToken: 'df_stf_8911',
    status: 'ACTIVE',
    bloodGroup: 'B+',
    emergencyContact: '+91 522 400 9999 (Admin Cell)',
    createdAt: '2025-03-10T09:00:00Z',
    updatedAt: '2025-03-10T09:00:00Z',
  },
  {
    id: 'card-stf-00002',
    staffId: 'DF-STF-2026-00002',
    staffName: 'Sayed Farhan',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    designation: 'Branch Administrator & Registrar',
    department: 'Administrative Governance & Admissions',
    branchName: 'DARULFAHAM Central Campus',
    joiningDate: '2024-11-01',
    qrCodeData: 'https://darulfaham.edu.in/verify/id?cardId=DF-STF-2026-00002&token=df_stf_4102',
    verificationToken: 'df_stf_4102',
    status: 'ACTIVE',
    bloodGroup: 'A+',
    emergencyContact: '+91 522 400 9999 (Admin Cell)',
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
  }
];

export const INITIAL_ID_CARD_SETTINGS: IdCardSettings = {
  studentPrefix: 'DF-STU',
  staffPrefix: 'DF-STF',
  academicYear: '2026',
  nextStudentSequence: 5,
  nextStaffSequence: 3,
  institutionName: 'DARULFAHAM',
  motto: 'Learn. Practice. Succeed.',
  address: '4th Floor, Civil Towers, Hazratganj Main Blvd, Lucknow - 226001',
  contactEmail: 'contact@darulfaham.edu.in',
  contactPhone: '+91 522 400 1234',
  emergencyHelpline: '+91 522 400 9999',
  allowPhoneOnStudentCard: false,
  qrVerificationBaseUrl: 'https://darulfaham.edu.in/verify/id',
  defaultValidityMonths: 12,
};

export const INITIAL_WEBHOOK_EVENTS: PaymentWebhookEvent[] = [
  {
    id: 'wev-001',
    eventId: 'cf_evt_991823',
    orderId: 'ord-1001',
    eventType: 'PAYMENT_SUCCESS_WEBHOOK',
    status: 'SUCCESS',
    amount: 1400,
    signatureVerified: true,
    receivedAt: '2026-08-01T10:16:35Z',
    processed: true,
  }
];

export const INITIAL_NOTICES: StudentNotice[] = [
  {
    id: 'not-001',
    title: 'Sanctum Air Conditioning & Power Inverter Scheduled Maintenance',
    content: 'Room 101 & Room 102 silent sanctums will undergo scheduled HVAC filter cleaning this Sunday from 06:00 AM to 08:00 AM. Study spaces remain fully accessible with backup ventilation.',
    category: 'STUDY_SPACE',
    date: '2026-09-06',
    priority: 'HIGH',
    author: 'Sanctum Facilities Desk',
  },
  {
    id: 'not-002',
    title: 'All-India UPSC Prelims Mock Examination 12 Announced',
    content: 'Constitutional Law & Governance full-length mock test will be uploaded to the Test Series engine on Monday. Please ensure your digital token is synchronized before beginning.',
    category: 'EXAM',
    date: '2026-09-04',
    priority: 'NORMAL',
    author: 'Academic Directorate',
  },
  {
    id: 'not-003',
    title: 'Geofence Verification Radius & Face Recognition Foundation Active',
    content: 'Aspirants can now record their daily check-in seamlessly when physically present at DARULFAHAM Hazratganj premises (within 100 meters). Camera snapshot verification is enabled.',
    category: 'ANNOUNCEMENT',
    date: '2026-09-02',
    priority: 'HIGH',
    author: 'Security & Attendance Cell',
  },
  {
    id: 'not-004',
    title: 'DARULFAHAM Digital Library: 4 New Polity & Ethics Compendiums Added',
    content: 'Standard reference compendiums for General Studies Paper II and Paper IV are now available for reading and offline study in the Digital Books repository.',
    category: 'STUDY_SPACE',
    date: '2026-08-28',
    priority: 'NORMAL',
    author: 'Librarian & Curations',
  },
];

